---
{{- if eq .Values.ingress.enabled true }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "dummyserver.fullname" . }}
  labels:
    {{- include "dummyserver.labels" . | nindent 4 }}
  annotations:
    {{- range $key,$val := .Values.ingress.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: /stats
        backend:
          service:
            name: {{ include "dummyserver.fullname" . }}
            port:
              number: {{ .Values.service.mgmtPort }}
      - pathType: Prefix
        path: /history
        backend:
          service:
            name: {{ include "dummyserver.fullname" . }}
            port:
              number: {{ .Values.service.mgmtPort }}
      - pathType: Prefix
        path: /clear
        backend:
          service:
            name: {{ include "dummyserver.fullname" . }}
            port:
              number: {{ .Values.service.mgmtPort }}
      - pathType: Prefix
        path: {{ .Values.ingress.basepath }}
        backend:
          service:
            name: {{ include "dummyserver.fullname" . }}
            port:
              number: {{ .Values.service.httpPort }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
{{- end }}